BoxLayout:
    orientation: 'vertical'

    BoxLayout:
        orientation: 'horizontal'

        TextInput:
            id: input_miles
            text: '0'
            on_text: app.convert(self.text)

        BoxLayout:
            orientation: 'vertical'
            size_hint_x: 0.3

            Button:
                text: 'Up'
                on_press: app.handle_increment(input_miles.text, 1)

            Button:
                text: 'Down'
                on_press: app.handle_increment(input_miles.text, -1)

    Label:
        text: app.output_text
        color: (1, 1, 0, 1)
        size_hint_y: 0.3
