BoxLayout:
    orientation: 'vertical'

    BoxLayout:
        orientation: 'horizontal'

        TextInput:
            id: input_number
            text: ''
            input_filter: 'int'

        Button:
            text: 'Square'
            on_press: app.handle_calculate(input_number.text)

        Label:
            id: output_label
            text: '?'
            color: (1, 0.5, 0.5, 1)

    Label:
        text: 'Enter a number and press "Square"'
        size_hint_y: 0.2
